/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPalpitesRouteImport } from './routes/_authenticated/palpites'
import { Route as AuthenticatedBonusRouteImport } from './routes/_authenticated/bonus'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPalpitesRoute = AuthenticatedPalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBonusRoute = AuthenticatedBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jogos': typeof JogosRoute
  '/ranking': typeof RankingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/palpites': typeof AuthenticatedPalpitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jogos': typeof JogosRoute
  '/ranking': typeof RankingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/palpites': typeof AuthenticatedPalpitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/jogos': typeof JogosRoute
  '/ranking': typeof RankingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bonus': typeof AuthenticatedBonusRoute
  '/_authenticated/palpites': typeof AuthenticatedPalpitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jogos'
    | '/ranking'
    | '/admin'
    | '/bonus'
    | '/palpites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/jogos' | '/ranking' | '/admin' | '/bonus' | '/palpites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/jogos'
    | '/ranking'
    | '/_authenticated/admin'
    | '/_authenticated/bonus'
    | '/_authenticated/palpites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JogosRoute: typeof JogosRoute
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/palpites': {
      id: '/_authenticated/palpites'
      path: '/palpites'
      fullPath: '/palpites'
      preLoaderRoute: typeof AuthenticatedPalpitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bonus': {
      id: '/_authenticated/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof AuthenticatedBonusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBonusRoute: typeof AuthenticatedBonusRoute
  AuthenticatedPalpitesRoute: typeof AuthenticatedPalpitesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBonusRoute: AuthenticatedBonusRoute,
  AuthenticatedPalpitesRoute: AuthenticatedPalpitesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JogosRoute: JogosRoute,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
